### ISSUE TITLE
Cursive anchors?

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/ShowAnchorCloud#11]
That is probably out of scope for this plugin, but if not I might give supporting cursive anchor a try (it would draw a “cloud” of the glyphs at the other side of the cursive connection).

**Comment by florianpircher** [comment]
I assume you would want this for Arabic? Then the number of possible glyph connections on either side is quite large. Do you think the visualization would still be useful? Or would there have to be a reduced set of candidates?

**Comment by simoncozens** [comment]
For most people (i.e. those making simplified Naskh designs) it won't actually be that many glyphs in practice. It's only us mad folks doing Ruqaa and Nastaliq who *heavily* use cursive anchors, and we can turn it off...

**Comment by khaledhosny** [comment]
It looks beautiful (now I have some artwork ideas), but not as useful as imagined it would be.
<img width="575" alt="image" src="https://github.com/user-attachments/assets/1228094e-b7d5-4e0a-8125-7e24a78eef1f">
