### ISSUE TITLE
Glyphs in Mark cloud in Glyphs.app

### ISSUE THREAD

**Issue by schriftgestalt** [simoncozens/ShowAnchorCloud#2]
this is just an informational post:
Glyphs doesn’t select the marked to show in the cloud based of some name heuristics. It is defined in the GlyphData for each glyph. That can be overwritten by custom GlyphData.

**Comment by simoncozens** [comment]
Yes, true. I should reword the description. The plugin still has value as it means people can work on marks without having to define their own GlyphData.

**Comment by schriftgestalt** [comment]
There is a plugin that displays all marks that are in the same Edit view.

**Comment by khaledhosny** [comment]
I find this plugin very useful as it can show any mark that attaches to the selected anchor. I have fonts with custom glyph names and this plugin handles them, I also often attach marks to glyphs other than what is defined in GlyphsData, which is handled here as well.
