### ISSUE TITLE
feature request: a simple way to turn off all anchors?

### ISSUE THREAD

**Issue by n7s** [simoncozens/ShowAnchorCloud#6]
An extra feature request to this awesome plugin:

Our type designers would find it very useful to be able to turn off all anchors in one single action (like a menu entry) and then be able to select only a few to focus on. Having to turn off a bunch of them one by one when working on those special glyphs with loads of anchors is getting a bit slow and annoying. Thanks!

**Comment by simoncozens** [comment]
Hah, I added this locally a long time ago and never committed it. Enjoy.
